name: Django CI Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      run: make install PYTHON=python

    - name: Run Django Tests
      run: make test PYTHON=python

    - name: Run Flake8 (Lint)
      run: make lint PYTHON=python

    - name: Run Bandit (Security & Code Smells)
      run: |
        python -m pip install bandit --quiet
        bandit -r accounts/ blog/ config/ -ll